### ISSUE TITLE
(Arduino) Pro Micro support

### ISSUE THREAD

**Issue by Producdevity** [artseyio/zmk-artsey#6]
I am new to this so please be easy on me if this is a stupid question.

The list for ZMK "The Paintbrush" releases doesn't seem to have a version for an Arduino Pro Micro. I do have a Nice Nano laying around but I just wired everything up to a Pro Micro (should have done it the other way around, note to self for next time haha)

So my question is if it is supported and with one I should download. Thanks a lot!

**Comment by mcrosson** [comment]
ZMK does not support 'arduino' pro micros. they only support a few forms of pro micro and have a compatability breakdown in their docs

if you have an avr pro micro youll need the qmk version of artsey
